### PR TITLE
Rg/feature/dashboard layout

### PR DESCRIPTION
**Pull request by reesegreen2014**
## Description of Changes
This PR introduces key updates to the dashboard and navigation functionality. These changes include: 
- Initial structure and styling of the dashboard page to match the provided Miro comp, utilizing mock data until fetch requests replace this later in development. 
- Implement conditional rendering for the header based on the user's logged-in state.
- Integration of responsive design.
- Addition of a protected route for the dashboard to ensure that only logged-in users can access it (thanks for your assistance with this, @kiewi16!)
- Logo is now clickable and directs to the home page
- The navigation bar has been updated to link to the login page and will adjust dynamically based on the user's authentication state.
- Local storage has been implemented to maintain the user's logged-in state, updating the UI accordingly (nav bar changes on logged-in v. logged-out)

## What are the relevant tickets (if any) 
- This PR is related to issues #37  #18 #34, and will be closed upon successful merge of this PR request.

## Screenshots (if applicable)
image
image
image

## Testing
User testing has been conducted to ensure the navigation works as behaved, including conditional rendering based on authentication state. Further testing will be conducted in Cypress in later development.

## Checklist
- [X] The code follows the project's coding standards.
- [ ] Unit tests have been added or updated to cover the changes. - N/A
- [X] Documentation has been updated to reflect the changes (if applicable). - N/A
- [X] The code compiles without errors. 
- [X] The changes have been tested locally and pass all relevant tests.
- [ ] All new and existing tests pass - N/A
- [x] The pull request has been reviewed by at least one other contributor.

## Reviewer Instructions
Please review the changes, particularly relating to the header conditional rendering based on a user being logged in or logged out, and also check the protected route for the dashboard by attempting to access `localhost:3000/dashboard` while being logged out to ensure this routes you to the login page. 

## Deployment Notes
No deployment instructions are required for this PR. 

## Additional Information
N/A at this time.

### CODE REVIEW

**Review by kiewi16 — COMMENTED** [review]
Question - do we need the console.log on line 64 in Login.tsx?

**Comment by kiewi16** [comment]
Hi Reese - nice work on this PR! I confirmed the following and I left one minor comment in the code review. 

- [x] Initial structure and styling of the dashboard page matches the provided Miro comp
- [x] Conditional rendering for the navigation bard based on the user's logged-in state has been successfully implemented. The navigation bar has been updated to link to the login page and will adjust dynamically based on the user's authentication state.The dashboard link does not appear in the navigation bar until the user has been authenticated. 
- [x] Responsive design has been integrated on the landing page and dashboard.
- [x] Protected route has been successfully implemented so a user cannot manually navigate to /dashboard unless they have logged in. The user is routed to the login page if they attempt to manually navigate to /dashboard. 
- [x] Logo is now clickable and directs to the home page
- [x] Local storage has been implemented to maintain the user's logged-in state, updating the UI accordingly (nav bar changes on logged-in v. logged-out)
- [x] Verified log out functionality: Ensured that after logging out, the user cannot manually access the /dashboard page, even if they were previously logged in during the same session.

**Comment by kiewi16** [comment]
QUESTION - there is a Draft ticket assigned to you under Ready "Landing Page (Hide Dashboard Button)"  that I believe should be linked to the PR.

**Comment by reesegreen2014** [comment]
> Question - do we need the console.log on line 64 in Login.tsx?

@kiewi16 Thank you for calling this out! I will remove this in the next branch. I put this in to view the response we were receiving from the backend upon successful login.

> QUESTION - there is a Draft ticket assigned to you under Ready "Landing Page (Hide Dashboard Button)" that I believe should be linked to the PR.

Great catch! I have linked it to this PR.

**Comment by kiewi16** [comment]
Reese - thank you for addressing my comments! I am going to merge this to main.

**Pull request merged**
